name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run the Docker image
      run: |
        docker pull ghcr.io/hell-pokemon/special-octo-waddle:latest
        docker run --name app1 -p 8000:8000 -d ghcr.io/hell-pokemon/special-octo-waddle:latest
        
